apiVersion: v2
name: testcreator
description: English Exam Builder - FastAPI + PostgreSQL
type: application
version: 0.1.0
appVersion: 'latest'

dependencies:
  - name: postgresql
    version: '18.8.0'
    repository: 'https://charts.bitnami.com/bitnami'
